// Automatically generated by makemoduledefs.py.

#if (MICROPY_PY_ARRAY)
    extern const struct _mp_obj_module_t mp_module_array;
    #define MODULE_DEF_MP_QSTR_ARRAY { MP_ROM_QSTR(MP_QSTR_array), MP_ROM_PTR(&mp_module_array) },
#else
    #define MODULE_DEF_MP_QSTR_ARRAY
#endif

#if (MODULE_ULAB_ENABLED)
    extern const struct _mp_obj_module_t ulab_user_cmodule;
    #define MODULE_DEF_MP_QSTR_ULAB { MP_ROM_QSTR(MP_QSTR_ulab), MP_ROM_PTR(&ulab_user_cmodule) },
#else
    #define MODULE_DEF_MP_QSTR_ULAB
#endif


#define MICROPY_REGISTERED_MODULES \
    MODULE_DEF_MP_QSTR_ARRAY \
    MODULE_DEF_MP_QSTR_ULAB \
// MICROPY_REGISTERED_MODULES
